{{- if and .Values.dataPersistency.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "lnd.persistenVolumeName" . }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.dataPersistency.storageClass }}
  volumeMode: {{ .Values.dataPersistency.volumeMode }}
  persistentVolumeReclaimPolicy: {{ .Values.dataPersistency.persistentVolumeReclaimPolicy }}

  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ include "lnd.persistenVolumeName" . }}

  capacity:
    storage: {{ .Values.dataPersistency.capacity }}
  
  accessModes:
    {{- range $.Values.dataPersistency.accessModes }}
    - {{ . }}
    {{- end }}

  {{- toYaml .Values.dataPersistency.providerPvConfig | nindent 2 }}
{{- end }}
