{{- if and .Values.dataPersistency.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "lnd.persistenVolumeName" . }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.dataPersistency.storageClass }}
  volumeMode: {{ .Values.dataPersistency.volumeMode }}
  capacity:
    storage: {{ .Values.dataPersistency.capacity }}
  persistentVolumeReclaimPolicy: {{ .Values.dataPersistency.persistentVolumeReclaimPolicy }}
  accessModes:
    {{- range $.Values.dataPersistency.accessModes }}
    - {{ . }}
    {{- end }}
  hostPath:
    path: {{ .Values.dataPersistency.diskMountPath }}
{{- end }}
