---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lnd.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "lnd.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "lnd.fullname" . }}
    namespace: base-challenge
