{{- if and .Values.dataPersistency.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.dataPersistency.storageClass }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}  
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}