{{- if and .Values.dataPersistency.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bitcoind.persistenVolumeName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range $.Values.dataPersistency.accessModes }}
    - {{ . }}
    {{- end }}

  resources:
    requests:
      storage: {{ .Values.dataPersistency.capacity }}    

  storageClassName: {{ .Values.dataPersistency.storageClass }}
{{- end }}
