apiVersion: v1
kind: Service
metadata:
  name: {{ include "c-lightning.serviceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "c-lightning.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "c-lightning.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIp }}
  ports:
    {{- range $.Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | quote }}
      name: {{ .name | quote }}
    {{- end }}

