apiVersion: v2
name: bitcoin-core
description: A Helm chart for Bitcoin core client
type: application
version: 0.1.0
appVersion: 0.21.0
dependencies: # A list of the chart requirements (optional)
  - name: bitcoin-core
    version: 0.1.0
    repository: gs://hodlone-helm-repo
  - name: lnd
    version: 0.1.0
    repository: gs://hodlone-helm-repo
maintainers: # (optional)
  - name: The maintainers name (required for each maintainer)
    email: The maintainers email (optional for each maintainer)
    url: A URL for the maintainer (optional for each maintainer)
