{{- if and .Values.dataPersistency.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.dataPersistency.volumeName }}
spec:
  storageClassName: {{ .Values.dataPersistency.storageClass }}
  capacity:
    storage: {{ .Values.dataPersistency.capacity }}
  accessModes:
    {{- range $.Values.dataPersistency.accessModes }}
    - {{ . }}
    {{- end }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.dataPersistency.volumeName }}

  {{- toYaml .Values.dataPersistency.providerPvConfig | nindent 2 }}
{{- end }}