###################################################################################
##################################### REPLICAS ####################################
###################################################################################
replicaCount: 1

###################################################################################
####################################### IMAGE #####################################
###################################################################################
image:
  name: "gcr.io/nodehodl/lnd"
  tag: latest
  #pullPolicy: IfNotPresent # Always


###################################################################################
##################################### SERVICE #####################################
###################################################################################
service:
  #nameOverride: "dummy-service"
  type: "ClusterIP" 
  clusterIp: "None" # can be set to "None" for headless services
  ports: 
    - port: 9735
      targetPort: 9735
      protocol: TCP
      name: p2p-mainnet
    - port: 10009
      targetPort: 10009
      protocol: TCP
      name: rpc

###################################################################################
################################## container ports ##################################
###################################################################################
containerPorts:
  - containerPort: 9735
    protocol: TCP
    name: p2p-mainnet
  - containerPort: 10009
    protocol: TCP
    name: rpc

###################################################################################
################################## NODE SELECTOR ##################################
###################################################################################
nodeSelectorEnabled: false
nodeSelector:
  preemptible: "false"

###################################################################################
################################# SECURITY CONTEXT ################################
###################################################################################
securityContext:
  enabled: false
  runAsUser: 100
  allowPrivilegeEscalation: false

###################################################################################
###################################### COMMAND ####################################
###################################################################################
command: 
  enabled: true
  args: [
    "--bitcoin.active",
    "--bitcoin.mainnet",
    "--debuglevel=debug",
    "--bitcoin.node=bitcoind",
    "--bitcoind.rpcuser=REPLACEME",
    "--bitcoind.rpcpass=REPLACEME",
    "--bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332",
    "--bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333",
    "--externalip=X.X.X.X"
  ]

###################################################################################
##################################### RESOURCES ###################################
###################################################################################
resources:
  requests:
    memory: "1Gi"
    cpu: "0.1"
    ephemeral-storage: "1Gi"
  limits:
    memory: "2Gi"
    cpu: "0.6"
    ephemeral-storage: "10Gi"

###################################################################################
##################################### PROBES ######################################
###################################################################################
# use a generous grace period to avoid long resyncs (rolling forward) at restart
# when the node receives SIGINT directive from kubernetes, it initiates a propper 
# shutdown process that takes time... 300 seconds seems to be enough time. 
terminationGracePeriodSeconds: 300
probesEnabled: false
livenessProbe:
  exec:
    command:
      - bitcoin-cli
      - getblockcount
  # use generous initial delay. if the node was NOT propperly shutdown before, 
  # the resync (rolling forward) will last for several hours before it is complete...
  # during this time, all CLI commands will fail and kubernetes will kill the pod 
  # and cause it to crashloop. 300 seconds seems to be enough in normal conditions
  initialDelaySeconds: 300 
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1

readinessProbe:
  exec:
    command:
      - bitcoin-cli
      - getblockcount
  # use generous initial delay. if the node was NOT propperly shutdown before, 
  # the resync (rolling forward) will last for several hours before it is complete...
  # during this time, all CLI commands will fail and kubernetes will kill the pod 
  # and cause it to crashloop. 300 seconds seems to be enough in normal conditions
  initialDelaySeconds: 300
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1


###################################################################################
################################ DATA PERSISTENCY #################################
###################################################################################
dataPersistency:
  enabled: true
  testMode: false # uses a different persistent volume for test purposes
  storageClass: bitcoin-core-data
  volumeMode: "Filesystem"
  mountPath: /home/bitcoin/.bitcoin
  capacity: "450Gi"
  accessModes: 
    - ReadWriteOnce
  diskMountPath: /mnt/bitcoin-data
  persistentVolumeReclaimPolicy: Retain

