name: "Chart Testing" 

on:
  pull_request:
    branches:
      - master

jobs:
  helm:
    runs-on: "ubuntu-latest"

    env:
      HELM_VERSION: "3.11.2"
      HELM_CT_VERSION: "3.7.1"

    steps:
      # checkout the code (git clone with fetch-depth=0... use 1 to fetch only the HEAD reference)
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # setup helm environment
      - name: Setup Helm v${{ env.HELM_VERSION }} Environment
        run: |
          set -o errexit
          echo '=====> Setting up HELM'
          wget -q https://get.helm.sh/helm-v${{ env.HELM_VERSION }}-linux-amd64.tar.gz -P tmp
          tar -zxf tmp/helm-v${{ env.HELM_VERSION }}-linux-amd64.tar.gz
          ls -al tmp
          sudo mv tmp/linux-amd64/helm /usr/local/bin/helm
          rm -rf tmp 
      
      # setup helm chart-testing environment and its dependencies
      - name: Setup Chart-Testing v${{ env.HELM_CT_VERSION }} Environment
        run: |
          echo '=====> Installing yamllint'
          sudo apt install yamllint  
          echo '=====> Installing yamale'
          wget -q https://github.com/23andMe/Yamale/archive/master.zip -P tmp
          unzip tmp/master.zip
          sudo python3 tmp/Yamale-master/setup.py install
          rm -rf tmp

          echo '=====> Installing ct (chart-testing)'
          wget -q https://github.com/helm/chart-testing/releases/download/v${{ env.HELM_CT_VERSION }}/chart-testing_${{ env.HELM_CT_VERSION }}_linux_amd64.tar.gz -P tmp
          tar -zxf tmp/chart-testing_${{ env.HELM_CT_VERSION }}_linux_amd64.tar.gz
          sudo mv tmp/ct /usr/local/bin/ct
          mkdir ~/.ct
          mv tmp/etc/*.yaml ~/.ct/
          rm -rf tmp
      
      # Test the charts that have changed (compared to master branch)
      - name: Test Charts
        run: ct lint $(ct list-changed)

      # package all charts in the `charts` directory
      - name: Package Charts
        run: make

      # generates an updated index
      - name: Generate new index
        run: make index

      # push all artifacts (chart tarballs and index manifest) to the current branch 
      - name: Push Generated Artifacts
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[CI] "
          commit_message: "Automated charts packages and index update"
          target_branch: ${{ github.head_ref }}